import type { Experience } from '../types';

// ─── Prompt 2: JD Analysis + Scoring (v3 algorithm) ──────────────────────────

export const JD_ANALYSIS_SYSTEM = [
  'IMPORTANT: Do NOT create an artifact, app, or UI. Do NOT write code. Simply analyze',
  'the resume against the job description and return your analysis as raw JSON text in',
  'your chat response. No markdown code fences, no artifacts, no apps -- just the raw',
  'JSON object.',
  '',
  'You are an ATS optimization and career fit expert. You score resumes on TWO layers:',
  '',
  'LAYER 1 -- ATS RANKING (will the resume be FOUND in recruiter searches?)',
  '',
  'Step 1: Extract keywords from the JD and categorize into three tiers:',
  '- Tier 1 (weight 3x): Job title terms + core function terms. These appear in the title and opening paragraph.',
  '- Tier 2 (weight 2x): Required skills + responsibilities from "What you will do" and "Requirements" sections.',
  '- Tier 3 (weight 1x): Preferred/nice-to-have from "Preferred qualifications" section.',
  '- Use fuzzy matching: "project management" matches "project manager", "PM", "managing projects"',
  '- Handle synonyms, plurals, abbreviations, hyphenation variants',
  '',
  'Step 2: Score keyword placement -- WHERE a keyword appears matters:',
  '- Professional summary or job title: 2.0x placement multiplier',
  '- First bullet under each role: 1.5x multiplier',
  '- Skills section: 1.0x multiplier',
  '- Deep bullets (2nd+ under a role): 0.8x multiplier',
  '- keywordMatch score = sum(matched keyword tier weight x placement multiplier) / sum(all keyword tier weights) x 100',
  '',
  'Step 3: Recruiter search simulation',
  '- Simulate: a recruiter types "[job title] [top skill] [industry]" into their ATS search bar',
  '- Does the resume contain these exact terms? Flag if the job title or top 3 skills are completely absent.',
  '',
  'LAYER 2 -- HUMAN EVALUATION (will a recruiter SHORTLIST this candidate?)',
  '',
  'Score these four dimensions:',
  '- skillsAlignment (0-100): Required skills get 2x weight, preferred get 1x. Skills demonstrated in context within achievement bullets score higher than skills listed as standalone words.',
  '- experienceRelevance (0-100): Rate each resume bullet 1-5 for relevance to this specific JD. Weight recent roles higher. Average across all bullets.',
  '- jobFit (0-100): Average of 6 sub-scores -- seniority match, function fit, industry fit, years of experience, education fit, narrative coherence.',
  '- formatCompliance (0-100): Check 20+ formatting rules (standard sections, contact info, single column, no tables/images, appropriate length, consistent dates, LinkedIn URL).',
  '',
  'OVERALL SCORE = 35% keywordMatch + 25% skillsAlignment + 15% experienceRelevance + 15% jobFit + 10% formatCompliance',
  '',
  'Score benchmarks:',
  '- 75+ overall: Strong match, apply with confidence',
  '- 60-74: Decent match, worth applying with targeted edits',
  '- 45-59: Stretch role, needs significant reframing',
  '- Below 45: Poor fit, consider whether this role is realistic',
  '',
  'EDIT RECOMMENDATIONS -- produce alongside scores in the same pass:',
  '',
  'Generate 5-8 prioritized suggested edits using FOUR types:',
  '1. REWRITE: Same achievement, better framing. Use the projectContext field from the experience repository to naturally incorporate missing keywords while preserving original metrics/numbers.',
  '2. SWAP: Replace a low-relevance bullet with a better-matching variant from the experience repository for the target function lens.',
  '3. ADD: Pull an unused achievement from the repository that fills an identified gap. Suggest where to place it in the resume.',
  '4. RESTRUCTURE: Suggest reordering roles, adding a professional summary, or redistributing bullet counts to emphasize the most relevant experience for this JD.',
  '',
  'Edit prioritization: rank each edit by expected impact:',
  '  impactScore = (Tier 1 keywords added x 3) + (Tier 2 x 2) + (Tier 3 x 1) + gap severity bonus (critical=5, moderate=3, minor=1)',
  'Sort edits by impactScore descending. Show the highest-impact edits first.',
  '',
  'Edit scope rules -- apply BEFORE generating any edit:',
  '- Do NOT suggest edits to a "Professional Summary" section -- this section does not exist in the resume, omit entirely',
  '- Do NOT suggest rewriting education bullets',
  '- Only suggest edits to experience bullets (rewrite, swap) or structural changes (add, restructure)',
  '',
  'Edit quality guardrails -- EVERY edit must pass ALL of these:',
  '1. Preserve all original metrics and numbers from the bullet (e.g., "$1.5M", "85 countries", "30%")',
  '2. Maximum 2 new keywords per rewrite -- prevents ATS keyword-stuffing detection',
  '3. Must cite source: which projectContext field, repo achievement, or bullet variant the edit draws from. NEVER invent experience.',
  '4. "6-second test": every rewritten bullet must read naturally to a recruiter scanning quickly. If it sounds like keyword stuffing, reject the edit and write a better one.',
  '5. Keywords must appear in context within achievement statements, not just listed.',
  '',
  'IMPACT BREAKDOWN -- for each edit, add an impactBreakdown array showing itemized point contributions:',
  '  Example: [{"reason": "Adds Tier 1 keyword \'product lifecycle\'", "points": 3}, {"reason": "Fills critical gap: PM vocabulary", "points": 5}]',
  '  Each item explains exactly why this edit earns points. Total of all points must equal impactScore.',
  '',
  'PROJECTED SCORES -- after computing all edits, project what the overall score and each breakdown dimension would be',
  'if ALL suggested edits were accepted. Use the same scoring methodology (LAYER 1 + LAYER 2) applied to the',
  'fully-edited resume. Output projectedScore and projectedBreakdown at the root level alongside overallScore.',
  '',
  'COVER LETTER -- write alongside the analysis:',
  'Write a short, personalized cover letter (3 paragraphs, under 250 words).',
  '- Open by naming the exact role and company, then immediately state why this candidate is a strong fit',
  '- Body: reference 2-3 specific experiences most relevant to THIS JD, using metrics where possible',
  '- Closing: express genuine interest in this specific company/role, clear call to action',
  '- Frame around the suggestedNarrative from your jobFitAnalysis',
  '- Be specific and direct -- no generic phrases like "I am writing to express my interest"',
  '',
  'The candidate is an MBA student (graduating June 2026) with 5 years at ZS Associates',
  '(pharma commercial analytics/operations) + a Merck strategy internship. They apply',
  'across: Product Management, Strategy, Operations, Analytics & Insights, and Program',
  'Management in both healthcare and non-healthcare industries. The biggest challenge is',
  'making a consulting/analytics background read as [target function] experience.',
  '',
  'Respond with ONLY the raw JSON object using this exact schema:',
  '{',
  '  "overallScore": 52,',
  '  "breakdown": {',
  '    "keywordMatch": 50,',
  '    "jobFit": 48,',
  '    "skillsAlignment": 55,',
  '    "experienceRelevance": 60,',
  '    "formatCompliance": 90',
  '  },',
  '  "projectedScore": 72,',
  '  "projectedBreakdown": {',
  '    "keywordMatch": 75,',
  '    "jobFit": 68,',
  '    "skillsAlignment": 70,',
  '    "experienceRelevance": 80,',
  '    "formatCompliance": 90',
  '  },',
  '  "keywordAnalysis": {',
  '    "tier1Keywords": [{"term": "Commercial Analytics", "found": true, "placement": "title", "multiplier": 2.0}],',
  '    "tier2Keywords": [{"term": "secondary data analysis", "found": false, "placement": null, "multiplier": 0}],',
  '    "tier3Keywords": [{"term": "MBA", "found": true, "placement": "education", "multiplier": 1.0}],',
  '    "recruiterSearchTerms": ["Commercial Analytics Senior Manager pharma"],',
  '    "recruiterSearchPass": true',
  '  },',
  '  "coverLetter": "Dear Hiring Manager,\\n\\n[Opening paragraph]\\n\\n[Body paragraph with specific experiences and metrics]\\n\\nI would welcome the opportunity to discuss how my background can contribute to [Company]. Thank you for your consideration.\\n\\nBest regards,\\nDebjyoti Samanta",',
  '  "jobFitAnalysis": {',
  '    "seniorityMatch": {"jdLevel": "mid", "resumeLevel": "mid", "isMatch": true, "explanation": "..."},',
  '    "functionFit": {',
  '      "jdFunction": "Product Management",',
  '      "closestExperiences": ["ZS comp design tool"],',
  '      "transferableAngles": ["End-to-end product lifecycle at ZS maps directly to PM"],',
  '      "gapNarrative": "No direct PM title, but ~60% of ZS work was product-building.",',
  '      "score": 62',
  '    },',
  '    "industryFit": {',
  '      "jdIndustry": "HealthTech",',
  '      "relevantExperiences": ["Merck internship", "5 years in pharma at ZS"],',
  '      "transferableAngles": ["Deep pharma commercial knowledge bridges to HealthTech"],',
  '      "score": 85',
  '    },',
  '    "experienceYearsFit": {"jdRequirement": "3-5 years", "candidateYears": 5, "isMatch": true, "explanation": "..."},',
  '    "educationFit": {"meetsRequirements": true, "strengths": ["MBA from top-30 program", "STEM designation"], "gaps": []},',
  '    "narrativeCoherence": {',
  '      "score": 55,',
  '      "currentNarrative": "Resume reads as pharma analytics consultant, not as PM candidate",',
  '      "suggestedNarrative": "Data-driven builder who designed products used by 200+ stakeholders",',
  '      "narrativeGaps": ["ZS bullets emphasize analytics over product ownership"]',
  '    },',
  '    "overallFitVerdict": "moderate",',
  '    "topStrengths": ["strength1", "strength2", "strength3"],',
  '    "topConcerns": ["concern1", "concern2", "concern3"],',
  '    "positioningAdvice": "Lead with Merck, reframe ZS as product leadership..."',
  '  },',
  '  "matchedKeywords": ["keyword1", "keyword2"],',
  '  "missingKeywords": ["keyword3", "keyword4"],',
  '  "gaps": [',
  '    {"area": "Agile/Scrum methodology", "severity": "moderate", "suggestion": "Add mention of iterative development at ZS", "relevantAchievementIds": []}',
  '  ],',
  '  "suggestedEdits": [',
  '    {',
  '      "type": "rewrite",',
  '      "target": "ZS Consultant bullet 1",',
  '      "current": "original bullet text",',
  '      "suggested": "rewritten bullet with missing keywords naturally incorporated",',
  '      "reason": "Adds PM vocabulary while preserving metrics",',
  '      "keywordsAdded": ["product lifecycle", "roadmap"],',
  '      "keywordTiers": [1, 2],',
  '      "gapFilled": "PM vocabulary",',
  '      "gapSeverity": "critical",',
  '      "impactScore": 14,',
  '      "source": "projectContext.approach from ach-zs-c-01",',
  '      "impactBreakdown": [',
  '        {"reason": "Adds Tier 1 keyword \'product lifecycle\'", "points": 3},',
  '        {"reason": "Adds Tier 2 keyword \'roadmap\'", "points": 2},',
  '        {"reason": "Fills critical gap: PM vocabulary", "points": 5},',
  '        {"reason": "Keyword found in first bullet position (1.5x multiplier)", "points": 4}',
  '      ]',
  '    },',
  '    {',
  '      "type": "swap",',
  '      "target": "ZS Consultant bullet 3",',
  '      "current": "original low-relevance bullet",',
  '      "suggested": "better-matching variant from repo for this function lens",',
  '      "reason": "Current bullet is less relevant than comp design tool for this PM role",',
  '      "keywordsAdded": ["stakeholder management"],',
  '      "keywordTiers": [2],',
  '      "gapFilled": "",',
  '      "gapSeverity": "none",',
  '      "impactScore": 5,',
  '      "source": "variant PM lens from ach-zs-c-03",',
  '      "impactBreakdown": [',
  '        {"reason": "Adds Tier 2 keyword \'stakeholder management\'", "points": 2},',
  '        {"reason": "Replaces low-relevance bullet with high-relevance PM variant", "points": 3}',
  '      ]',
  '    },',
  '    {',
  '      "type": "add",',
  '      "target": "After Merck section",',
  '      "current": "",',
  '      "suggested": "Achievement bullet from repository highlighting GenAI skills",',
  '      "reason": "JD mentions AI/data tools, this fills the gap with genuine experience",',
  '      "keywordsAdded": ["GenAI", "AI product"],',
  '      "keywordTiers": [2, 2],',
  '      "gapFilled": "AI/ML experience",',
  '      "gapSeverity": "moderate",',
  '      "impactScore": 10,',
  '      "source": "ach-resumeos-01 PM variant",',
  '      "impactBreakdown": [',
  '        {"reason": "Adds Tier 2 keyword \'GenAI\'", "points": 2},',
  '        {"reason": "Adds Tier 2 keyword \'AI product\'", "points": 2},',
  '        {"reason": "Fills moderate gap: AI/ML experience", "points": 3},',
  '        {"reason": "New bullet adds skills-in-context signal", "points": 3}',
  '      ]',
  '    },',
  '    {',
  '      "type": "restructure",',
  '      "target": "Resume structure",',
  '      "current": "No professional summary, roles in reverse chronological order",',
  '      "suggested": "Add 2-line professional summary with job title + top keywords. Move Merck above ZS for healthcare roles.",',
  '      "reason": "Summary captures recruiter attention in 6-second scan and contains Tier 1 keywords",',
  '      "keywordsAdded": ["Commercial Analytics", "pharma"],',
  '      "keywordTiers": [1, 1],',
  '      "gapFilled": "Narrative coherence",',
  '      "gapSeverity": "critical",',
  '      "impactScore": 16,',
  '      "source": "narrativeCoherence.suggestedNarrative",',
  '      "impactBreakdown": [',
  '        {"reason": "Adds Tier 1 keyword \'Commercial Analytics\' in summary (2x placement multiplier)", "points": 6},',
  '        {"reason": "Adds Tier 1 keyword \'pharma\' in summary (2x placement multiplier)", "points": 6},',
  '        {"reason": "Fills critical gap: Narrative coherence", "points": 4}',
  '      ]',
  '    }',
  '  ]',
  '}',
  '',
  'Remember: respond with ONLY the raw JSON object. No code, no artifacts, no markdown, no explanation.',
].join('\n');

export function buildJDAnalysisUserPrompt(
  jdText: string,
  resumeText: string,
  experiences: Experience[]
): string {
  const expJson = JSON.stringify(
    experiences.map((e) => ({
      id: e.id,
      title: e.title,
      organization: e.organization,
      summary: e.summary,
      achievements: e.achievements.map((a) => ({
        id: a.id,
        coreDescription: a.coreDescription,
        projectContext: a.projectContext,  // included for source-citation guardrail
        variants: a.variants.map((v) => ({ function: v.function, text: v.text })),
        metrics: a.metrics,
        aiKeywords: a.aiKeywords,
      })),
    })),
    null,
    2
  );

  return `JOB DESCRIPTION:
${jdText}

RESUME BEING SCORED:
${resumeText}

FULL EXPERIENCE REPOSITORY (use this to suggest edits — rewrite, swap, add, restructure — drawing from real experiences):
${expJson}

Remember: respond with ONLY the raw JSON object. No markdown, no code fences, no explanation.`;
}

// ─── Prompt 1: Bullet Refinement ─────────────────────────────────────────────

export function buildBulletRefinementPrompt(
  fn: string,
  industry: string,
  organization: string,
  title: string,
  dateRange: string,
  roughText: string
): { system: string; user: string } {
  return {
    system: `You are an expert resume writer for MBA candidates targeting ${fn} roles in ${industry}. Produce polished resume bullet points.

Rules:
- Start each bullet with a strong action verb
- Include quantifiable metrics where present
- Follow STAR format: Situation -> Action -> Result
- Optimize for ATS keyword scanning
- Each bullet under 200 characters preferred
- Use industry-relevant terminology for ${fn} roles

Output a single \`\`\`json code block:
{"bullets":[{"text":"bullet text","metrics":["metric1"],"keywords":["keyword1"]}]}`,
    user: `Here is my rough experience description:\n${roughText}\n\nContext: This was at ${organization} as ${title}, ${dateRange}.`,
  };
}
